# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: matrix-appservice-irc
summary: matrix-appservice-irc snap
description: An IRC bridge for Matrix
version: "3.0.2"
base: core22
license: Apache-2.0
confinement: strict
architectures:
  - build-on: [amd64]
    build-for: [amd64]
issues: https://github.com/canonical/matrix-appservice-irc/issues
source-code: https://github.com/canonical/matrix-appservice-irc
website: https://github.com/canonical/matrix-appservice-irc
icon: icon.png

plugs:
  etc-matrix-appservice-irc:
    interface: system-files
    read:
    - /etc/matrix-appservice-irc
    write:
    - /etc/matrix-appservice-irc
apps:
  matrix-appservice-irc:
    #command: "bin/node $SNAP/app.js -c /data/config.yaml -f /data/appservice-registration-irc.yaml"
    command: "bin/matrix-appservice-irc-wrapper.sh"
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - etc-matrix-appservice-irc
      - home
    environment:
      LD_PRELOAD: "$SNAP/libfreebindfree.so"
parts:
  node:
    plugin: dump
    source: https://nodejs.org/dist/v20.2.0/node-v20.2.0-linux-x64.tar.xz
    stage:
      - bin
      - include
      - lib
  freebindfree:
    plugin: make
    source: https://github.com/matrix-org/freebindfree.git
    override-build: |
      make
      mv libfreebindfree.so $CRAFT_PRIME/
  matrix-appservice-irc:
    after: [node, freebindfree]
    plugin: dump
    source: https://github.com/matrix-org/matrix-appservice-irc.git
    source-tag: 3.0.2
    source-type: git
    override-build: |
      npm install -g yarn
      npm install @matrix-org/matrix-sdk-crypto-nodejs
      yarn --strict-semver --frozen-lockfile
      rm -rf node_modules
      yarn cache clean
      yarn install --production
      mkdir app
      mv package.json app/
      mv public app/
      mv app.js app/
      mv config.schema.yml app/
      mv node_modules app/
      mv lib app/
      mv app/ $CRAFT_PRIME/
    stage-packages: [sipcalc, iproute2, openssl, libatm1, musl]
  matrix-appservice-irc-wrapper:
    after: [node, freebindfree, matrix-appservice-irc]
    plugin: dump
    source: .
    override-prime: |
      craftctl default
      cp matrix-appservice-irc-wrapper.sh $SNAPCRAFT_PRIME/bin/
      chmod +x $SNAPCRAFT_PRIME/bin/matrix-appservice-irc-wrapper.sh
